### ISSUE TITLE
Aktualizacja rozdziałów do wersji z głównego repozytorium progit2

### ISSUE THREAD

**Issue by davpal** [progit2-pl/progit2-pl#19]
Nasze repo pozostało daleko w tyle z historią, więc zrobienie zwyklego merga z progit2/main jest zbyt trudne.
Jeśli zabieramy się z tłumaczenie nowego pliku polecałbym rozpoczecie pracy od zaktualizowania go do wersji z repozytorium progit2.

Na początek potrzebny jest remote:
`git remote add progit https://github.com/progit/progit2.git`

Pobieramy zmiany:
`git fetch progit`

Checkoutujemy wersję z progit2 np.
`git checkout progit/main -- book/03-git-branching/sections/workflows.asc`

Teraz można zamieniać tekst na polski. Gdyby w pliku były odnośniki do np. rysunków, które zostały przeniesione również należałoby wycheckoutować z progit wszystkie zależności danego rozdziału.

Tłumaczenia, które zostały już przeniesione z progit1 należałoby porównać z wersją z progit2. Czasem dodawane są pojedyncze zdania lub podobne małe zmiany.

**Comment by olsza** [comment]
Proponuję, takie "zgłoszenia" czy dyskusję przenieść do https://github.com/progit2-pl/progit2-pl/discussions

Ogólnie plan mój jest taki,że będzie klon main ze źródła EN do main naszego Repo i tam przenieść tłumaczenia, które są z wersji 1, ale zauważyłem,że pokrywa się ok 98% a te 2% różnią się tym,że brakuje jakiś linków (odsyłaczy) lub jakiś dodatkowych informacji (notatek)

ps. ten wątek zamknę gdy stworze branch `main` ;)

**Comment by olsza** [comment]
Zamyka, jest otwarta [dyskusja "Reaktywacja"](#24) na ten temat.
